name: ⭐Integration Test ⭐

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  Android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Download Android Command Line Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      - name: Set up Android SDK environment
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: AVD Install
        run: |
          yes | sdkmanager "system-images;android-35;google_apis;x86_64"
          echo no | avdmanager create avd -n testEmulator -k "system-images;android-35;google_apis;x86_64"
          sdkmanager "platform-tools"
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Start AVD
        run: |
          $HOME/android-sdk/emulator/emulator -avd testEmulator -no-window -no-audio &
          adb wait-for-device
          bootcompleted=""
          until [ "$bootcompleted" == "1" ]; do
            sleep 5
            bootcompleted=$(adb shell getprop sys.boot_completed | tr -d '\r\n')
          done
          echo "Initialized Emulator"

      - name: Run create_image_from_pdf_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_image_from_pdf_integration_test.dart -d testEmulator

      - name: Run create_pdf_from_multiple_images_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_pdf_from_multiple_images_integration_test.dart -d testEmulator

      - name: Run merge_multiple_pdfs_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/merge_multiple_pdfs_integration_test.dart -d testEmulator