name: Integration Test - Android

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  android-integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Moves to the example project
        run: cd example

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          script: flutter --no-color test --machine -d android integration_test