name: Integration Test - Android

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Moves to the example project
        run: cd example

      - name: Setup AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          disable-animations: true
          script: echo "Emulator ready!"

      - name: Run integration tests
        run: flutter --no-color test --machine -d android integration_test
