name: Dart

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Run tests
        run: flutter test