name: ⭐ Integration Test ⭐ iOS

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  Testing:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MacOS Dependencies
        run: |
          sudo gem install cocoapods
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Enable Flutter for iOS
        run: flutter config --enable-ios

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Start iOS Simulator
        run: |
          UDID=$(xcrun simctl list devices available | grep "iPhone 16" | head -n 1 | awk -F'[()]' '{print $2}')
          if [ -z "$UDID" ]; then
            echo "No available iPhone 16 simulator found."
            exit 1
          fi
          echo "Using simulator: $UDID"
          xcrun simctl boot "$UDID"
          echo "Wait for iOS Simulator to Boot Completely"
          xcrun simctl bootstatus "$UDID" -b
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

      - name: Ensure Flutter Detects the Simulator
        run: flutter devices

      - name: Run create_image_from_pdf_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_image_from_pdf_integration_test.dart

      - name: Run create_pdf_from_multiple_images_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_pdf_from_multiple_images_integration_test.dart

      - name: Run merge_multiple_pdfs_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/merge_multiple_pdfs_integration_test.dart
