name: Integration Test - Linux

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  android-integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests
        script:
          run example && flutter test integration_test -d linux