name: ⭐ Integration Test ⭐

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  MacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MacOS Dependencies
        run: |
          sudo gem install cocoapods

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run create_image_from_pdf_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_image_from_pdf_integration_test.dart -d macos

      - name: Run create_pdf_from_multiple_images_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/create_pdf_from_multiple_images_integration_test.dart -d macos

      - name: Run merge_multiple_pdfs_integration_test Integration Tests
        run: |
          cd example
          flutter test integration_test/merge_multiple_pdfs_integration_test.dart -d macos